// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/monitorv1/monitor.proto

package monitorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlaybackMonitorService_IngestSessionEvent_FullMethodName           = "/muxcore.playback.monitor.v1.PlaybackMonitorService/IngestSessionEvent"
	PlaybackMonitorService_ListActiveSessions_FullMethodName           = "/muxcore.playback.monitor.v1.PlaybackMonitorService/ListActiveSessions"
	PlaybackMonitorService_ListHistory_FullMethodName                  = "/muxcore.playback.monitor.v1.PlaybackMonitorService/ListHistory"
	PlaybackMonitorService_GetHomeStats_FullMethodName                 = "/muxcore.playback.monitor.v1.PlaybackMonitorService/GetHomeStats"
	PlaybackMonitorService_GetItemWatchStats_FullMethodName            = "/muxcore.playback.monitor.v1.PlaybackMonitorService/GetItemWatchStats"
	PlaybackMonitorService_ListWatchUsers_FullMethodName               = "/muxcore.playback.monitor.v1.PlaybackMonitorService/ListWatchUsers"
	PlaybackMonitorService_GetStreamAnalytics_FullMethodName           = "/muxcore.playback.monitor.v1.PlaybackMonitorService/GetStreamAnalytics"
	PlaybackMonitorService_ListUserWatchStats_FullMethodName           = "/muxcore.playback.monitor.v1.PlaybackMonitorService/ListUserWatchStats"
	PlaybackMonitorService_ListServers_FullMethodName                  = "/muxcore.playback.monitor.v1.PlaybackMonitorService/ListServers"
	PlaybackMonitorService_RegisterServer_FullMethodName               = "/muxcore.playback.monitor.v1.PlaybackMonitorService/RegisterServer"
	PlaybackMonitorService_GetPlaysByDate_FullMethodName               = "/muxcore.playback.monitor.v1.PlaybackMonitorService/GetPlaysByDate"
	PlaybackMonitorService_GetPlaysByHour_FullMethodName               = "/muxcore.playback.monitor.v1.PlaybackMonitorService/GetPlaysByHour"
	PlaybackMonitorService_GetPlaysByDayOfWeek_FullMethodName          = "/muxcore.playback.monitor.v1.PlaybackMonitorService/GetPlaysByDayOfWeek"
	PlaybackMonitorService_GetPlaysByMonth_FullMethodName              = "/muxcore.playback.monitor.v1.PlaybackMonitorService/GetPlaysByMonth"
	PlaybackMonitorService_GetPlaysByStreamType_FullMethodName         = "/muxcore.playback.monitor.v1.PlaybackMonitorService/GetPlaysByStreamType"
	PlaybackMonitorService_GetPlaysByStreamResolution_FullMethodName   = "/muxcore.playback.monitor.v1.PlaybackMonitorService/GetPlaysByStreamResolution"
	PlaybackMonitorService_GetPlaysBySourceResolution_FullMethodName   = "/muxcore.playback.monitor.v1.PlaybackMonitorService/GetPlaysBySourceResolution"
	PlaybackMonitorService_GetPlaysByPlatformResolution_FullMethodName = "/muxcore.playback.monitor.v1.PlaybackMonitorService/GetPlaysByPlatformResolution"
	PlaybackMonitorService_GetPlaysByTopUsers_FullMethodName           = "/muxcore.playback.monitor.v1.PlaybackMonitorService/GetPlaysByTopUsers"
	PlaybackMonitorService_GetPlaysByTopPlatforms_FullMethodName       = "/muxcore.playback.monitor.v1.PlaybackMonitorService/GetPlaysByTopPlatforms"
	PlaybackMonitorService_GetConcurrentStreams_FullMethodName         = "/muxcore.playback.monitor.v1.PlaybackMonitorService/GetConcurrentStreams"
	PlaybackMonitorService_MergeUserIdentity_FullMethodName            = "/muxcore.playback.monitor.v1.PlaybackMonitorService/MergeUserIdentity"
	PlaybackMonitorService_ImportTautulliHistory_FullMethodName        = "/muxcore.playback.monitor.v1.PlaybackMonitorService/ImportTautulliHistory"
	PlaybackMonitorService_ImportJellystatHistory_FullMethodName       = "/muxcore.playback.monitor.v1.PlaybackMonitorService/ImportJellystatHistory"
	PlaybackMonitorService_DeleteUserHistory_FullMethodName            = "/muxcore.playback.monitor.v1.PlaybackMonitorService/DeleteUserHistory"
	PlaybackMonitorService_ListLibraryStats_FullMethodName             = "/muxcore.playback.monitor.v1.PlaybackMonitorService/ListLibraryStats"
	PlaybackMonitorService_ListLibraryDuplicates_FullMethodName        = "/muxcore.playback.monitor.v1.PlaybackMonitorService/ListLibraryDuplicates"
	PlaybackMonitorService_ListStaleLibraryItems_FullMethodName        = "/muxcore.playback.monitor.v1.PlaybackMonitorService/ListStaleLibraryItems"
	PlaybackMonitorService_GetLibraryStorageSummary_FullMethodName     = "/muxcore.playback.monitor.v1.PlaybackMonitorService/GetLibraryStorageSummary"
	PlaybackMonitorService_GetLibraryStorageHistory_FullMethodName     = "/muxcore.playback.monitor.v1.PlaybackMonitorService/GetLibraryStorageHistory"
	PlaybackMonitorService_ListTopContent_FullMethodName               = "/muxcore.playback.monitor.v1.PlaybackMonitorService/ListTopContent"
)

// PlaybackMonitorServiceClient is the client API for PlaybackMonitorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlaybackMonitorServiceClient interface {
	IngestSessionEvent(ctx context.Context, in *IngestSessionEventRequest, opts ...grpc.CallOption) (*IngestSessionEventResponse, error)
	ListActiveSessions(ctx context.Context, in *ListActiveSessionsRequest, opts ...grpc.CallOption) (*ListActiveSessionsResponse, error)
	ListHistory(ctx context.Context, in *ListHistoryRequest, opts ...grpc.CallOption) (*ListHistoryResponse, error)
	GetHomeStats(ctx context.Context, in *GetHomeStatsRequest, opts ...grpc.CallOption) (*GetHomeStatsResponse, error)
	GetItemWatchStats(ctx context.Context, in *GetItemWatchStatsRequest, opts ...grpc.CallOption) (*GetItemWatchStatsResponse, error)
	ListWatchUsers(ctx context.Context, in *ListWatchUsersRequest, opts ...grpc.CallOption) (*ListWatchUsersResponse, error)
	GetStreamAnalytics(ctx context.Context, in *GetStreamAnalyticsRequest, opts ...grpc.CallOption) (*GetStreamAnalyticsResponse, error)
	ListUserWatchStats(ctx context.Context, in *ListUserWatchStatsRequest, opts ...grpc.CallOption) (*ListUserWatchStatsResponse, error)
	ListServers(ctx context.Context, in *ListServersRequest, opts ...grpc.CallOption) (*ListServersResponse, error)
	RegisterServer(ctx context.Context, in *RegisterServerRequest, opts ...grpc.CallOption) (*RegisterServerResponse, error)
	GetPlaysByDate(ctx context.Context, in *GetPlaysByDateRequest, opts ...grpc.CallOption) (*GetPlaysByDateResponse, error)
	GetPlaysByHour(ctx context.Context, in *GetPlaysByHourRequest, opts ...grpc.CallOption) (*GetPlaysByHourResponse, error)
	GetPlaysByDayOfWeek(ctx context.Context, in *GetPlaysByDayOfWeekRequest, opts ...grpc.CallOption) (*GetPlaysByDayOfWeekResponse, error)
	GetPlaysByMonth(ctx context.Context, in *GetPlaysByMonthRequest, opts ...grpc.CallOption) (*GetPlaysByMonthResponse, error)
	GetPlaysByStreamType(ctx context.Context, in *GetPlaysByStreamTypeRequest, opts ...grpc.CallOption) (*GetPlaysByStreamTypeResponse, error)
	GetPlaysByStreamResolution(ctx context.Context, in *GetPlaysByStreamResolutionRequest, opts ...grpc.CallOption) (*GetPlaysByStreamResolutionResponse, error)
	GetPlaysBySourceResolution(ctx context.Context, in *GetPlaysBySourceResolutionRequest, opts ...grpc.CallOption) (*GetPlaysBySourceResolutionResponse, error)
	GetPlaysByPlatformResolution(ctx context.Context, in *GetPlaysByPlatformResolutionRequest, opts ...grpc.CallOption) (*GetPlaysByPlatformResolutionResponse, error)
	GetPlaysByTopUsers(ctx context.Context, in *GetPlaysByTopUsersRequest, opts ...grpc.CallOption) (*GetPlaysByTopUsersResponse, error)
	GetPlaysByTopPlatforms(ctx context.Context, in *GetPlaysByTopPlatformsRequest, opts ...grpc.CallOption) (*GetPlaysByTopPlatformsResponse, error)
	GetConcurrentStreams(ctx context.Context, in *GetConcurrentStreamsRequest, opts ...grpc.CallOption) (*GetConcurrentStreamsResponse, error)
	MergeUserIdentity(ctx context.Context, in *MergeUserIdentityRequest, opts ...grpc.CallOption) (*MergeUserIdentityResponse, error)
	ImportTautulliHistory(ctx context.Context, in *ImportTautulliHistoryRequest, opts ...grpc.CallOption) (*ImportTautulliHistoryResponse, error)
	ImportJellystatHistory(ctx context.Context, in *ImportJellystatHistoryRequest, opts ...grpc.CallOption) (*ImportJellystatHistoryResponse, error)
	DeleteUserHistory(ctx context.Context, in *DeleteUserHistoryRequest, opts ...grpc.CallOption) (*DeleteUserHistoryResponse, error)
	ListLibraryStats(ctx context.Context, in *ListLibraryStatsRequest, opts ...grpc.CallOption) (*ListLibraryStatsResponse, error)
	ListLibraryDuplicates(ctx context.Context, in *ListLibraryDuplicatesRequest, opts ...grpc.CallOption) (*ListLibraryDuplicatesResponse, error)
	ListStaleLibraryItems(ctx context.Context, in *ListStaleLibraryItemsRequest, opts ...grpc.CallOption) (*ListStaleLibraryItemsResponse, error)
	GetLibraryStorageSummary(ctx context.Context, in *GetLibraryStorageSummaryRequest, opts ...grpc.CallOption) (*GetLibraryStorageSummaryResponse, error)
	GetLibraryStorageHistory(ctx context.Context, in *GetLibraryStorageHistoryRequest, opts ...grpc.CallOption) (*GetLibraryStorageHistoryResponse, error)
	ListTopContent(ctx context.Context, in *ListTopContentRequest, opts ...grpc.CallOption) (*ListTopContentResponse, error)
}

type playbackMonitorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlaybackMonitorServiceClient(cc grpc.ClientConnInterface) PlaybackMonitorServiceClient {
	return &playbackMonitorServiceClient{cc}
}

func (c *playbackMonitorServiceClient) IngestSessionEvent(ctx context.Context, in *IngestSessionEventRequest, opts ...grpc.CallOption) (*IngestSessionEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestSessionEventResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_IngestSessionEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) ListActiveSessions(ctx context.Context, in *ListActiveSessionsRequest, opts ...grpc.CallOption) (*ListActiveSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActiveSessionsResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_ListActiveSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) ListHistory(ctx context.Context, in *ListHistoryRequest, opts ...grpc.CallOption) (*ListHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHistoryResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_ListHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) GetHomeStats(ctx context.Context, in *GetHomeStatsRequest, opts ...grpc.CallOption) (*GetHomeStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHomeStatsResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_GetHomeStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) GetItemWatchStats(ctx context.Context, in *GetItemWatchStatsRequest, opts ...grpc.CallOption) (*GetItemWatchStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemWatchStatsResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_GetItemWatchStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) ListWatchUsers(ctx context.Context, in *ListWatchUsersRequest, opts ...grpc.CallOption) (*ListWatchUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWatchUsersResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_ListWatchUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) GetStreamAnalytics(ctx context.Context, in *GetStreamAnalyticsRequest, opts ...grpc.CallOption) (*GetStreamAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStreamAnalyticsResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_GetStreamAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) ListUserWatchStats(ctx context.Context, in *ListUserWatchStatsRequest, opts ...grpc.CallOption) (*ListUserWatchStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserWatchStatsResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_ListUserWatchStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) ListServers(ctx context.Context, in *ListServersRequest, opts ...grpc.CallOption) (*ListServersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServersResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_ListServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) RegisterServer(ctx context.Context, in *RegisterServerRequest, opts ...grpc.CallOption) (*RegisterServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterServerResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_RegisterServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) GetPlaysByDate(ctx context.Context, in *GetPlaysByDateRequest, opts ...grpc.CallOption) (*GetPlaysByDateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaysByDateResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_GetPlaysByDate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) GetPlaysByHour(ctx context.Context, in *GetPlaysByHourRequest, opts ...grpc.CallOption) (*GetPlaysByHourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaysByHourResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_GetPlaysByHour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) GetPlaysByDayOfWeek(ctx context.Context, in *GetPlaysByDayOfWeekRequest, opts ...grpc.CallOption) (*GetPlaysByDayOfWeekResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaysByDayOfWeekResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_GetPlaysByDayOfWeek_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) GetPlaysByMonth(ctx context.Context, in *GetPlaysByMonthRequest, opts ...grpc.CallOption) (*GetPlaysByMonthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaysByMonthResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_GetPlaysByMonth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) GetPlaysByStreamType(ctx context.Context, in *GetPlaysByStreamTypeRequest, opts ...grpc.CallOption) (*GetPlaysByStreamTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaysByStreamTypeResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_GetPlaysByStreamType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) GetPlaysByStreamResolution(ctx context.Context, in *GetPlaysByStreamResolutionRequest, opts ...grpc.CallOption) (*GetPlaysByStreamResolutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaysByStreamResolutionResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_GetPlaysByStreamResolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) GetPlaysBySourceResolution(ctx context.Context, in *GetPlaysBySourceResolutionRequest, opts ...grpc.CallOption) (*GetPlaysBySourceResolutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaysBySourceResolutionResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_GetPlaysBySourceResolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) GetPlaysByPlatformResolution(ctx context.Context, in *GetPlaysByPlatformResolutionRequest, opts ...grpc.CallOption) (*GetPlaysByPlatformResolutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaysByPlatformResolutionResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_GetPlaysByPlatformResolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) GetPlaysByTopUsers(ctx context.Context, in *GetPlaysByTopUsersRequest, opts ...grpc.CallOption) (*GetPlaysByTopUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaysByTopUsersResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_GetPlaysByTopUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) GetPlaysByTopPlatforms(ctx context.Context, in *GetPlaysByTopPlatformsRequest, opts ...grpc.CallOption) (*GetPlaysByTopPlatformsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaysByTopPlatformsResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_GetPlaysByTopPlatforms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) GetConcurrentStreams(ctx context.Context, in *GetConcurrentStreamsRequest, opts ...grpc.CallOption) (*GetConcurrentStreamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConcurrentStreamsResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_GetConcurrentStreams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) MergeUserIdentity(ctx context.Context, in *MergeUserIdentityRequest, opts ...grpc.CallOption) (*MergeUserIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeUserIdentityResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_MergeUserIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) ImportTautulliHistory(ctx context.Context, in *ImportTautulliHistoryRequest, opts ...grpc.CallOption) (*ImportTautulliHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportTautulliHistoryResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_ImportTautulliHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) ImportJellystatHistory(ctx context.Context, in *ImportJellystatHistoryRequest, opts ...grpc.CallOption) (*ImportJellystatHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportJellystatHistoryResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_ImportJellystatHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) DeleteUserHistory(ctx context.Context, in *DeleteUserHistoryRequest, opts ...grpc.CallOption) (*DeleteUserHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserHistoryResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_DeleteUserHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) ListLibraryStats(ctx context.Context, in *ListLibraryStatsRequest, opts ...grpc.CallOption) (*ListLibraryStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLibraryStatsResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_ListLibraryStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) ListLibraryDuplicates(ctx context.Context, in *ListLibraryDuplicatesRequest, opts ...grpc.CallOption) (*ListLibraryDuplicatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLibraryDuplicatesResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_ListLibraryDuplicates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) ListStaleLibraryItems(ctx context.Context, in *ListStaleLibraryItemsRequest, opts ...grpc.CallOption) (*ListStaleLibraryItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStaleLibraryItemsResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_ListStaleLibraryItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) GetLibraryStorageSummary(ctx context.Context, in *GetLibraryStorageSummaryRequest, opts ...grpc.CallOption) (*GetLibraryStorageSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLibraryStorageSummaryResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_GetLibraryStorageSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) GetLibraryStorageHistory(ctx context.Context, in *GetLibraryStorageHistoryRequest, opts ...grpc.CallOption) (*GetLibraryStorageHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLibraryStorageHistoryResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_GetLibraryStorageHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbackMonitorServiceClient) ListTopContent(ctx context.Context, in *ListTopContentRequest, opts ...grpc.CallOption) (*ListTopContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTopContentResponse)
	err := c.cc.Invoke(ctx, PlaybackMonitorService_ListTopContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaybackMonitorServiceServer is the server API for PlaybackMonitorService service.
// All implementations must embed UnimplementedPlaybackMonitorServiceServer
// for forward compatibility.
type PlaybackMonitorServiceServer interface {
	IngestSessionEvent(context.Context, *IngestSessionEventRequest) (*IngestSessionEventResponse, error)
	ListActiveSessions(context.Context, *ListActiveSessionsRequest) (*ListActiveSessionsResponse, error)
	ListHistory(context.Context, *ListHistoryRequest) (*ListHistoryResponse, error)
	GetHomeStats(context.Context, *GetHomeStatsRequest) (*GetHomeStatsResponse, error)
	GetItemWatchStats(context.Context, *GetItemWatchStatsRequest) (*GetItemWatchStatsResponse, error)
	ListWatchUsers(context.Context, *ListWatchUsersRequest) (*ListWatchUsersResponse, error)
	GetStreamAnalytics(context.Context, *GetStreamAnalyticsRequest) (*GetStreamAnalyticsResponse, error)
	ListUserWatchStats(context.Context, *ListUserWatchStatsRequest) (*ListUserWatchStatsResponse, error)
	ListServers(context.Context, *ListServersRequest) (*ListServersResponse, error)
	RegisterServer(context.Context, *RegisterServerRequest) (*RegisterServerResponse, error)
	GetPlaysByDate(context.Context, *GetPlaysByDateRequest) (*GetPlaysByDateResponse, error)
	GetPlaysByHour(context.Context, *GetPlaysByHourRequest) (*GetPlaysByHourResponse, error)
	GetPlaysByDayOfWeek(context.Context, *GetPlaysByDayOfWeekRequest) (*GetPlaysByDayOfWeekResponse, error)
	GetPlaysByMonth(context.Context, *GetPlaysByMonthRequest) (*GetPlaysByMonthResponse, error)
	GetPlaysByStreamType(context.Context, *GetPlaysByStreamTypeRequest) (*GetPlaysByStreamTypeResponse, error)
	GetPlaysByStreamResolution(context.Context, *GetPlaysByStreamResolutionRequest) (*GetPlaysByStreamResolutionResponse, error)
	GetPlaysBySourceResolution(context.Context, *GetPlaysBySourceResolutionRequest) (*GetPlaysBySourceResolutionResponse, error)
	GetPlaysByPlatformResolution(context.Context, *GetPlaysByPlatformResolutionRequest) (*GetPlaysByPlatformResolutionResponse, error)
	GetPlaysByTopUsers(context.Context, *GetPlaysByTopUsersRequest) (*GetPlaysByTopUsersResponse, error)
	GetPlaysByTopPlatforms(context.Context, *GetPlaysByTopPlatformsRequest) (*GetPlaysByTopPlatformsResponse, error)
	GetConcurrentStreams(context.Context, *GetConcurrentStreamsRequest) (*GetConcurrentStreamsResponse, error)
	MergeUserIdentity(context.Context, *MergeUserIdentityRequest) (*MergeUserIdentityResponse, error)
	ImportTautulliHistory(context.Context, *ImportTautulliHistoryRequest) (*ImportTautulliHistoryResponse, error)
	ImportJellystatHistory(context.Context, *ImportJellystatHistoryRequest) (*ImportJellystatHistoryResponse, error)
	DeleteUserHistory(context.Context, *DeleteUserHistoryRequest) (*DeleteUserHistoryResponse, error)
	ListLibraryStats(context.Context, *ListLibraryStatsRequest) (*ListLibraryStatsResponse, error)
	ListLibraryDuplicates(context.Context, *ListLibraryDuplicatesRequest) (*ListLibraryDuplicatesResponse, error)
	ListStaleLibraryItems(context.Context, *ListStaleLibraryItemsRequest) (*ListStaleLibraryItemsResponse, error)
	GetLibraryStorageSummary(context.Context, *GetLibraryStorageSummaryRequest) (*GetLibraryStorageSummaryResponse, error)
	GetLibraryStorageHistory(context.Context, *GetLibraryStorageHistoryRequest) (*GetLibraryStorageHistoryResponse, error)
	ListTopContent(context.Context, *ListTopContentRequest) (*ListTopContentResponse, error)
	mustEmbedUnimplementedPlaybackMonitorServiceServer()
}

// UnimplementedPlaybackMonitorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlaybackMonitorServiceServer struct{}

func (UnimplementedPlaybackMonitorServiceServer) IngestSessionEvent(context.Context, *IngestSessionEventRequest) (*IngestSessionEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestSessionEvent not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) ListActiveSessions(context.Context, *ListActiveSessionsRequest) (*ListActiveSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActiveSessions not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) ListHistory(context.Context, *ListHistoryRequest) (*ListHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHistory not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) GetHomeStats(context.Context, *GetHomeStatsRequest) (*GetHomeStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHomeStats not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) GetItemWatchStats(context.Context, *GetItemWatchStatsRequest) (*GetItemWatchStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemWatchStats not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) ListWatchUsers(context.Context, *ListWatchUsersRequest) (*ListWatchUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWatchUsers not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) GetStreamAnalytics(context.Context, *GetStreamAnalyticsRequest) (*GetStreamAnalyticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStreamAnalytics not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) ListUserWatchStats(context.Context, *ListUserWatchStatsRequest) (*ListUserWatchStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserWatchStats not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) ListServers(context.Context, *ListServersRequest) (*ListServersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServers not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) RegisterServer(context.Context, *RegisterServerRequest) (*RegisterServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterServer not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) GetPlaysByDate(context.Context, *GetPlaysByDateRequest) (*GetPlaysByDateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaysByDate not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) GetPlaysByHour(context.Context, *GetPlaysByHourRequest) (*GetPlaysByHourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaysByHour not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) GetPlaysByDayOfWeek(context.Context, *GetPlaysByDayOfWeekRequest) (*GetPlaysByDayOfWeekResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaysByDayOfWeek not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) GetPlaysByMonth(context.Context, *GetPlaysByMonthRequest) (*GetPlaysByMonthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaysByMonth not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) GetPlaysByStreamType(context.Context, *GetPlaysByStreamTypeRequest) (*GetPlaysByStreamTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaysByStreamType not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) GetPlaysByStreamResolution(context.Context, *GetPlaysByStreamResolutionRequest) (*GetPlaysByStreamResolutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaysByStreamResolution not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) GetPlaysBySourceResolution(context.Context, *GetPlaysBySourceResolutionRequest) (*GetPlaysBySourceResolutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaysBySourceResolution not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) GetPlaysByPlatformResolution(context.Context, *GetPlaysByPlatformResolutionRequest) (*GetPlaysByPlatformResolutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaysByPlatformResolution not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) GetPlaysByTopUsers(context.Context, *GetPlaysByTopUsersRequest) (*GetPlaysByTopUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaysByTopUsers not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) GetPlaysByTopPlatforms(context.Context, *GetPlaysByTopPlatformsRequest) (*GetPlaysByTopPlatformsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlaysByTopPlatforms not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) GetConcurrentStreams(context.Context, *GetConcurrentStreamsRequest) (*GetConcurrentStreamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConcurrentStreams not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) MergeUserIdentity(context.Context, *MergeUserIdentityRequest) (*MergeUserIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MergeUserIdentity not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) ImportTautulliHistory(context.Context, *ImportTautulliHistoryRequest) (*ImportTautulliHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportTautulliHistory not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) ImportJellystatHistory(context.Context, *ImportJellystatHistoryRequest) (*ImportJellystatHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportJellystatHistory not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) DeleteUserHistory(context.Context, *DeleteUserHistoryRequest) (*DeleteUserHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserHistory not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) ListLibraryStats(context.Context, *ListLibraryStatsRequest) (*ListLibraryStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLibraryStats not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) ListLibraryDuplicates(context.Context, *ListLibraryDuplicatesRequest) (*ListLibraryDuplicatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLibraryDuplicates not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) ListStaleLibraryItems(context.Context, *ListStaleLibraryItemsRequest) (*ListStaleLibraryItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStaleLibraryItems not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) GetLibraryStorageSummary(context.Context, *GetLibraryStorageSummaryRequest) (*GetLibraryStorageSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLibraryStorageSummary not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) GetLibraryStorageHistory(context.Context, *GetLibraryStorageHistoryRequest) (*GetLibraryStorageHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLibraryStorageHistory not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) ListTopContent(context.Context, *ListTopContentRequest) (*ListTopContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTopContent not implemented")
}
func (UnimplementedPlaybackMonitorServiceServer) mustEmbedUnimplementedPlaybackMonitorServiceServer() {
}
func (UnimplementedPlaybackMonitorServiceServer) testEmbeddedByValue() {}

// UnsafePlaybackMonitorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlaybackMonitorServiceServer will
// result in compilation errors.
type UnsafePlaybackMonitorServiceServer interface {
	mustEmbedUnimplementedPlaybackMonitorServiceServer()
}

func RegisterPlaybackMonitorServiceServer(s grpc.ServiceRegistrar, srv PlaybackMonitorServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlaybackMonitorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlaybackMonitorService_ServiceDesc, srv)
}

func _PlaybackMonitorService_IngestSessionEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestSessionEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).IngestSessionEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_IngestSessionEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).IngestSessionEvent(ctx, req.(*IngestSessionEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_ListActiveSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).ListActiveSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_ListActiveSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).ListActiveSessions(ctx, req.(*ListActiveSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_ListHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).ListHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_ListHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).ListHistory(ctx, req.(*ListHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_GetHomeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHomeStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).GetHomeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_GetHomeStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).GetHomeStats(ctx, req.(*GetHomeStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_GetItemWatchStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemWatchStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).GetItemWatchStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_GetItemWatchStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).GetItemWatchStats(ctx, req.(*GetItemWatchStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_ListWatchUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWatchUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).ListWatchUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_ListWatchUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).ListWatchUsers(ctx, req.(*ListWatchUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_GetStreamAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).GetStreamAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_GetStreamAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).GetStreamAnalytics(ctx, req.(*GetStreamAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_ListUserWatchStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserWatchStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).ListUserWatchStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_ListUserWatchStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).ListUserWatchStats(ctx, req.(*ListUserWatchStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_ListServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).ListServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_ListServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).ListServers(ctx, req.(*ListServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_RegisterServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).RegisterServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_RegisterServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).RegisterServer(ctx, req.(*RegisterServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_GetPlaysByDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaysByDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).GetPlaysByDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_GetPlaysByDate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).GetPlaysByDate(ctx, req.(*GetPlaysByDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_GetPlaysByHour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaysByHourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).GetPlaysByHour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_GetPlaysByHour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).GetPlaysByHour(ctx, req.(*GetPlaysByHourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_GetPlaysByDayOfWeek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaysByDayOfWeekRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).GetPlaysByDayOfWeek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_GetPlaysByDayOfWeek_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).GetPlaysByDayOfWeek(ctx, req.(*GetPlaysByDayOfWeekRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_GetPlaysByMonth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaysByMonthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).GetPlaysByMonth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_GetPlaysByMonth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).GetPlaysByMonth(ctx, req.(*GetPlaysByMonthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_GetPlaysByStreamType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaysByStreamTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).GetPlaysByStreamType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_GetPlaysByStreamType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).GetPlaysByStreamType(ctx, req.(*GetPlaysByStreamTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_GetPlaysByStreamResolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaysByStreamResolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).GetPlaysByStreamResolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_GetPlaysByStreamResolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).GetPlaysByStreamResolution(ctx, req.(*GetPlaysByStreamResolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_GetPlaysBySourceResolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaysBySourceResolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).GetPlaysBySourceResolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_GetPlaysBySourceResolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).GetPlaysBySourceResolution(ctx, req.(*GetPlaysBySourceResolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_GetPlaysByPlatformResolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaysByPlatformResolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).GetPlaysByPlatformResolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_GetPlaysByPlatformResolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).GetPlaysByPlatformResolution(ctx, req.(*GetPlaysByPlatformResolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_GetPlaysByTopUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaysByTopUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).GetPlaysByTopUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_GetPlaysByTopUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).GetPlaysByTopUsers(ctx, req.(*GetPlaysByTopUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_GetPlaysByTopPlatforms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaysByTopPlatformsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).GetPlaysByTopPlatforms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_GetPlaysByTopPlatforms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).GetPlaysByTopPlatforms(ctx, req.(*GetPlaysByTopPlatformsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_GetConcurrentStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConcurrentStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).GetConcurrentStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_GetConcurrentStreams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).GetConcurrentStreams(ctx, req.(*GetConcurrentStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_MergeUserIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeUserIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).MergeUserIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_MergeUserIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).MergeUserIdentity(ctx, req.(*MergeUserIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_ImportTautulliHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportTautulliHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).ImportTautulliHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_ImportTautulliHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).ImportTautulliHistory(ctx, req.(*ImportTautulliHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_ImportJellystatHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportJellystatHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).ImportJellystatHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_ImportJellystatHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).ImportJellystatHistory(ctx, req.(*ImportJellystatHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_DeleteUserHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).DeleteUserHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_DeleteUserHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).DeleteUserHistory(ctx, req.(*DeleteUserHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_ListLibraryStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLibraryStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).ListLibraryStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_ListLibraryStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).ListLibraryStats(ctx, req.(*ListLibraryStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_ListLibraryDuplicates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLibraryDuplicatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).ListLibraryDuplicates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_ListLibraryDuplicates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).ListLibraryDuplicates(ctx, req.(*ListLibraryDuplicatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_ListStaleLibraryItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStaleLibraryItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).ListStaleLibraryItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_ListStaleLibraryItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).ListStaleLibraryItems(ctx, req.(*ListStaleLibraryItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_GetLibraryStorageSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLibraryStorageSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).GetLibraryStorageSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_GetLibraryStorageSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).GetLibraryStorageSummary(ctx, req.(*GetLibraryStorageSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_GetLibraryStorageHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLibraryStorageHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).GetLibraryStorageHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_GetLibraryStorageHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).GetLibraryStorageHistory(ctx, req.(*GetLibraryStorageHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaybackMonitorService_ListTopContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTopContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybackMonitorServiceServer).ListTopContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaybackMonitorService_ListTopContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybackMonitorServiceServer).ListTopContent(ctx, req.(*ListTopContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlaybackMonitorService_ServiceDesc is the grpc.ServiceDesc for PlaybackMonitorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlaybackMonitorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muxcore.playback.monitor.v1.PlaybackMonitorService",
	HandlerType: (*PlaybackMonitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestSessionEvent",
			Handler:    _PlaybackMonitorService_IngestSessionEvent_Handler,
		},
		{
			MethodName: "ListActiveSessions",
			Handler:    _PlaybackMonitorService_ListActiveSessions_Handler,
		},
		{
			MethodName: "ListHistory",
			Handler:    _PlaybackMonitorService_ListHistory_Handler,
		},
		{
			MethodName: "GetHomeStats",
			Handler:    _PlaybackMonitorService_GetHomeStats_Handler,
		},
		{
			MethodName: "GetItemWatchStats",
			Handler:    _PlaybackMonitorService_GetItemWatchStats_Handler,
		},
		{
			MethodName: "ListWatchUsers",
			Handler:    _PlaybackMonitorService_ListWatchUsers_Handler,
		},
		{
			MethodName: "GetStreamAnalytics",
			Handler:    _PlaybackMonitorService_GetStreamAnalytics_Handler,
		},
		{
			MethodName: "ListUserWatchStats",
			Handler:    _PlaybackMonitorService_ListUserWatchStats_Handler,
		},
		{
			MethodName: "ListServers",
			Handler:    _PlaybackMonitorService_ListServers_Handler,
		},
		{
			MethodName: "RegisterServer",
			Handler:    _PlaybackMonitorService_RegisterServer_Handler,
		},
		{
			MethodName: "GetPlaysByDate",
			Handler:    _PlaybackMonitorService_GetPlaysByDate_Handler,
		},
		{
			MethodName: "GetPlaysByHour",
			Handler:    _PlaybackMonitorService_GetPlaysByHour_Handler,
		},
		{
			MethodName: "GetPlaysByDayOfWeek",
			Handler:    _PlaybackMonitorService_GetPlaysByDayOfWeek_Handler,
		},
		{
			MethodName: "GetPlaysByMonth",
			Handler:    _PlaybackMonitorService_GetPlaysByMonth_Handler,
		},
		{
			MethodName: "GetPlaysByStreamType",
			Handler:    _PlaybackMonitorService_GetPlaysByStreamType_Handler,
		},
		{
			MethodName: "GetPlaysByStreamResolution",
			Handler:    _PlaybackMonitorService_GetPlaysByStreamResolution_Handler,
		},
		{
			MethodName: "GetPlaysBySourceResolution",
			Handler:    _PlaybackMonitorService_GetPlaysBySourceResolution_Handler,
		},
		{
			MethodName: "GetPlaysByPlatformResolution",
			Handler:    _PlaybackMonitorService_GetPlaysByPlatformResolution_Handler,
		},
		{
			MethodName: "GetPlaysByTopUsers",
			Handler:    _PlaybackMonitorService_GetPlaysByTopUsers_Handler,
		},
		{
			MethodName: "GetPlaysByTopPlatforms",
			Handler:    _PlaybackMonitorService_GetPlaysByTopPlatforms_Handler,
		},
		{
			MethodName: "GetConcurrentStreams",
			Handler:    _PlaybackMonitorService_GetConcurrentStreams_Handler,
		},
		{
			MethodName: "MergeUserIdentity",
			Handler:    _PlaybackMonitorService_MergeUserIdentity_Handler,
		},
		{
			MethodName: "ImportTautulliHistory",
			Handler:    _PlaybackMonitorService_ImportTautulliHistory_Handler,
		},
		{
			MethodName: "ImportJellystatHistory",
			Handler:    _PlaybackMonitorService_ImportJellystatHistory_Handler,
		},
		{
			MethodName: "DeleteUserHistory",
			Handler:    _PlaybackMonitorService_DeleteUserHistory_Handler,
		},
		{
			MethodName: "ListLibraryStats",
			Handler:    _PlaybackMonitorService_ListLibraryStats_Handler,
		},
		{
			MethodName: "ListLibraryDuplicates",
			Handler:    _PlaybackMonitorService_ListLibraryDuplicates_Handler,
		},
		{
			MethodName: "ListStaleLibraryItems",
			Handler:    _PlaybackMonitorService_ListStaleLibraryItems_Handler,
		},
		{
			MethodName: "GetLibraryStorageSummary",
			Handler:    _PlaybackMonitorService_GetLibraryStorageSummary_Handler,
		},
		{
			MethodName: "GetLibraryStorageHistory",
			Handler:    _PlaybackMonitorService_GetLibraryStorageHistory_Handler,
		},
		{
			MethodName: "ListTopContent",
			Handler:    _PlaybackMonitorService_ListTopContent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/monitorv1/monitor.proto",
}
